package com;
// Generated Jun 16, 2019 12:33:08 AM by Hibernate Tools 4.3.1



/**
 * Category generated by hbm2java
 */
public class Category  implements java.io.Serializable {


     private int catId;
     private String catName;
     private String catDesc;

    public Category() {
    }

	
    public Category(int catId) {
        this.catId = catId;
    }
    public Category(int catId, String catName, String catDesc) {
       this.catId = catId;
       this.catName = catName;
       this.catDesc = catDesc;
    }
   
    public int getCatId() {
        return this.catId;
    }
    
    public void setCatId(int catId) {
        this.catId = catId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public String getCatDesc() {
        return this.catDesc;
    }
    
    public void setCatDesc(String catDesc) {
        this.catDesc = catDesc;
    }




}


