package com;
// Generated Jun 16, 2019 12:33:08 AM by Hibernate Tools 4.3.1



/**
 * Delivary generated by hbm2java
 */
public class Delivary  implements java.io.Serializable {


     private int delivaryId;
     private String zoneName;
     private String email;
     private String phone;
     private Integer delivaryCost;
     private String customerName;
     private String address;
     private int paytk;
     private String prodetail;
    public Delivary() {
    }

	
    public Delivary(int delivaryId) {
        this.delivaryId = delivaryId;
    }
    public Delivary(int delivaryId, String zoneName, String email, String phone, Integer delivaryCost,String customerName,String address, int paytk,String prodetail) {
       this.delivaryId = delivaryId;
       this.zoneName = zoneName;
       this.email = email;
       this.phone = phone;
       this.delivaryCost = delivaryCost;
       this.customerName = customerName;
       this.address=address;
       this.paytk = paytk;
       this.prodetail = prodetail; 
    }
   
    public int getDelivaryId() {
        return this.delivaryId;
    }
    
    public void setDelivaryId(int delivaryId) {
        this.delivaryId = delivaryId;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Integer getDelivaryCost() {
        return this.delivaryCost;
    }
    
    public void setDelivaryCost(Integer delivaryCost) {
        this.delivaryCost = delivaryCost;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public int getPaytk() {
        return paytk;
    }

    public void setPaytk(int paytk) {
        this.paytk = paytk;
    }

    public String getProdetail() {
        return prodetail;
    }

    public void setProdetail(String prodetail) {
        this.prodetail = prodetail;
    }




}


