package com;
// Generated Jun 16, 2019 12:33:08 AM by Hibernate Tools 4.3.1



/**
 * Order generated by hbm2java
 */
public class Order  implements java.io.Serializable {


     private Integer orderId;
     private Integer proId;
     private String proName;
     private Integer proQty;
     private Integer totalPrice;

    public Order() {
    }

    public Order(Integer proId, String proName, Integer proQty, Integer totalPrice) {
       this.proId = proId;
       this.proName = proName;
       this.proQty = proQty;
       this.totalPrice = totalPrice;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public Integer getProQty() {
        return this.proQty;
    }
    
    public void setProQty(Integer proQty) {
        this.proQty = proQty;
    }
    public Integer getTotalPrice() {
        return this.totalPrice;
    }
    
    public void setTotalPrice(Integer totalPrice) {
        this.totalPrice = totalPrice;
    }




}


