package com;
// Generated Jun 16, 2019 12:33:08 AM by Hibernate Tools 4.3.1



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer proId;
     private String catName;
     private String subCatName;
     private String proName;
     private Integer proQty;
     private Integer proPrice;
     private String proImg;
     private String proBrand;

    public Product() {
    }

    public Product(String catName, String subCatName, String proName, Integer proQty, Integer proPrice, String proImg, String proBrand) {
       this.catName = catName;
       this.subCatName = subCatName;
       this.proName = proName;
       this.proQty = proQty;
       this.proPrice = proPrice;
       this.proImg = proImg;
       this.proBrand = proBrand;
    }
   
    public Integer getProId() {
        return this.proId;
    }
    
    public void setProId(Integer proId) {
        this.proId = proId;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }
    public String getProName() {
        return this.proName;
    }
    
    public void setProName(String proName) {
        this.proName = proName;
    }
    public Integer getProQty() {
        return this.proQty;
    }
    
    public void setProQty(Integer proQty) {
        this.proQty = proQty;
    }
    public Integer getProPrice() {
        return this.proPrice;
    }
    
    public void setProPrice(Integer proPrice) {
        this.proPrice = proPrice;
    }
    public String getProImg() {
        return this.proImg;
    }
    
    public void setProImg(String proImg) {
        this.proImg = proImg;
    }
    public String getProBrand() {
        return this.proBrand;
    }
    
    public void setProBrand(String proBrand) {
        this.proBrand = proBrand;
    }




}


