package com;
// Generated Jun 16, 2019 12:33:08 AM by Hibernate Tools 4.3.1



/**
 * ShopUser generated by hbm2java
 */
public class ShopUser  implements java.io.Serializable {


     private Integer userId;
     private String userName;
     private String password;
     private String email;
     private String contactNo;

    public ShopUser() {
    }

    public ShopUser(String userName, String password, String email, String contactNo) {
       this.userName = userName;
       this.password = password;
       this.email = email;
       this.contactNo = contactNo;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }




}


