package com;
// Generated Jun 16, 2019 12:33:08 AM by Hibernate Tools 4.3.1



/**
 * SubCategory generated by hbm2java
 */
public class SubCategory  implements java.io.Serializable {
     private Integer subCatId;
     private String subCatName;
     private String subCatDesc;
     private String catName;

    public SubCategory() {
    }

    public SubCategory(String subCatName, String subCatDesc, String catName) {
       this.subCatName = subCatName;
       this.subCatDesc = subCatDesc;
       this.catName = catName;
    }
   
    public Integer getSubCatId() {
        return this.subCatId;
    }
    
    public void setSubCatId(Integer subCatId) {
        this.subCatId = subCatId;
    }
    public String getSubCatName() {
        return this.subCatName;
    }
    
    public void setSubCatName(String subCatName) {
        this.subCatName = subCatName;
    }
    public String getSubCatDesc() {
        return this.subCatDesc;
    }
    
    public void setSubCatDesc(String subCatDesc) {
        this.subCatDesc = subCatDesc;
    }
    public String getCatName() {
        return this.catName;
    }
    
    public void setCatName(String catName) {
        this.catName = catName;
    }




}


